config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :cart_products
  resources :carts
  root to: "pages#index"
  get 'pages/index'
  get 'pages/ovoce'
  get 'pages/zelenina'
  get 'pages/napoje'
  get 'users/show'

end

app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  include CurrentCart
  #before_action :set_cart, only: [:create]
  before_action :set_cart_final, only: [:create]
  before_action :set_cart_product, only: [:show, :edit, :update, :destroy]

  # GET /cart_products
  # GET /cart_products.json
  def index
    @cart_products = CartProduct.all
  end

  # GET /cart_products/1
  # GET /cart_products/1.json
  def show
  end

  # GET /cart_products/new
  def new
    @cart_product = CartProduct.new
  end

  # GET /cart_products/1/edit
  def edit
  end

  # POST /cart_products
  # POST /cart_products.json
  # add product to cart and assign cart to user if user logegd in. If there is cart already belongs to user
  # this cart is used instead of creating a new one
  def create
    product = Product.find(params[:product_id])
    quantity = params[:pocet]
    @cart_product = @cart.add_product(product.id, quantity)
    :add_cart_to_current_user
    respond_to do |format|
      if @cart_product.save
        if user_signed_in?
          user = current_user
          user.cart_id = @cart.id
          user.save
        end
        format.html { redirect_to @cart, notice: 'Zbozi bylo vlozeno do kosiku' }
        format.json { render :show, status: :created, location: @cart_product }
      else
        format.html { render :new }
        format.json { render json: @cart_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_products/1
  # PATCH/PUT /cart_products/1.json
  def update
    respond_to do |format|
      if @cart_product.update(cart_product_params)
        format.html { redirect_to pages_index_path, notice: 'Cart product was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_product }
      else
        format.html { render :edit }
        format.json { render json: @cart_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_products/1
  # DELETE /cart_products/1.json
  def destroy
    @cart_product.destroy
    respond_to do |format|
      format.html { redirect_to cart_products_url, notice: 'Cart product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_product
      @cart_product = CartProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_product_params
      params.require(:cart_product).permit(:product, :pocet)
    end

    # add cart_id to users table if user logged in
    def add_cart_to_current_user(cart_id)
      if user_signed_in
        user = current_user
        user.cart_id = cart_id
        user.save
      end
    end

    # set cart method.
    # if there is signed in user and cart in DB which belongs to that user, this cart is selected for adding product
    # to cart. In the other ways new cart is created.
    def set_cart_final
      if user_signed_in?
        user = current_user
        if user.cart_id != nil
          # logged user get cart which is in db belongs to this user.
          begin
            @cart = Cart.find(user.cart_id)
            session[:cart_id] = user.cart_id
          # if the cart desn't exists, new cart is created
          rescue ActiveRecord::RecordNotFound
            begin
              @cart = Cart.find(session[:cart_id])
            rescue ActiveRecord::RecordNotFound
              @cart = Cart.create
              session[:cart_id] = @cart.id
            end
          end
        end
      else
        # if user signed out, find session cart, rescuing to create new if session cart isnt find
        begin
          @cart = Cart.find(session[:cart_id])
        rescue ActiveRecord::RecordNotFound
          @cart = Cart.create
          session[:cart_id] = @cart.id
        end
      end
    end
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/_form.html.erb
<%= form_for(@cart_product) do |f| %>
  <% if @cart_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_product.errors.count, "error") %> prohibited this cart_product from being saved:</h2>

      <ul>
      <% @cart_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
    <%= f.text_field_tag 'quantity' %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_products/edit.html.erb
<h1>Editing Cart Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_product %> |
<%= link_to 'Back', cart_products_path %>

app/views/cart_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cart Products</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_products.each do |cart_product| %>
      <tr>
        <td><%= cart_product.product %></td>
        <td><%= cart_product.cart %></td>
        <td><%= link_to 'Show', cart_product %></td>
        <td><%= link_to 'Edit', edit_cart_product_path(cart_product) %></td>
        <td><%= link_to 'Destroy', cart_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart product', new_cart_product_path %>

app/views/cart_products/new.html.erb
<h1>New Cart Product</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_products_path %>

app/views/cart_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @cart_product.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @cart_product.cart %>
</p>

<%= link_to 'Edit', edit_cart_product_path(@cart_product) %> |
<%= link_to 'Back', cart_products_path %>